# Generated by Django 3.2.3 on 2021-12-14 16:53

from django.db import migrations, models
import uploadFile.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginUploadPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=uploadFile.models.plugin_pdf_upload_to)),
                ('category', models.CharField(max_length=400)),
            ],
        ),
    ]
