# Generated by Django 3.2.3 on 2021-12-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0002_pluginuploadpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_mail', models.CharField(max_length=100)),
                ('sender_pwd', models.CharField(max_length=100)),
                ('receiver_mail', models.CharField(max_length=100)),
            ],
        ),
    ]
